# Generated by Django 4.0.6 on 2022-07-21 06:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.CharField(max_length=200)),
                ('product_board', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('upload_date', models.DateTimeField()),
            ],
        ),
    ]
