# Generated by Django 4.0.6 on 2022-07-22 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_size',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
