# Generated by Django 4.0.6 on 2022-07-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_thumbnail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_size',
            field=models.CharField(max_length=200),
        ),
    ]
