# Generated by Django 4.0.6 on 2022-07-22 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_product_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_thumbnail',
        ),
    ]
